# Generated by Django 6.0 on 2026-01-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
