# Generated by Django 6.0 on 2026-01-14 17:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_code',
            field=models.CharField(blank=True, default=users.models.generate_agent_code, max_length=12, null=True, unique=True),
        ),
    ]
