# Generated by Django 6.0 on 2026-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
