# Generated by Django 6.0 on 2026-01-16 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='agent_api.agent')),
            ],
            options={
                'verbose_name_plural': 'Daily Activities',
                'indexes': [models.Index(fields=['agent', 'date'], name='agent_api_d_agent_i_59412d_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_activities', to='agent_api.agent')),
            ],
            options={
                'verbose_name_plural': 'Monthly Activities',
                'indexes': [models.Index(fields=['agent', 'date'], name='agent_api_m_agent_i_0217f5_idx')],
            },
        ),
    ]
