# Generated by Django 6.0 on 2026-01-16 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_dailyactivity_monthlyactivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['agent', 'timestamp'], name='agent_api_d_agent_i_a147d4_idx'),
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='last_updated',
        ),
    ]
