# Generated by Django 6.0 on 2026-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_alter_dailyactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='config_override',
        ),
        migrations.AddField(
            model_name='agent',
            name='daily_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agent',
            name='monthly_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
